-- Migração: "Histórico de Kilometragem" em Gestão de Frotas.
--
-- Pedido do Diego (02-06/10/2026): hoje só importamos do GPO os veículos
-- "EM USO" (94 de 662 no total) e nunca trouxemos o histórico de leituras
-- de KM que cada placa acumula (o que o GPO chama de "Histórico de
-- Kilometragem", visto na tela "Alterar Veículo" dele). O KM somado por
-- CONTRATO (que continua valendo entre trocas de placa) já é importado hoje
-- no campo veiculos.km_contrato — isso não muda. O que falta é:
--   1) trazer os veículos de TODOS os status (não só EM USO);
--   2) ter uma tabela própria pra guardar cada leitura periódica de KM por
--      veículo (placa), com um botão "Lançar Kilometragem" igual ao GPO.
-- Essa importação é ÚNICA (não uma sincronização contínua — o sistema
-- continua 100% independente do GPO depois, igual já decidido antes, ver
-- comentário em src/app/api/veiculos/route.ts). Depois dela, novas leituras
-- só entram por aqui mesmo, lançadas manualmente.
--
-- Como rodar: Supabase -> projeto Controle Eolen -> SQL Editor -> New query
-- -> cola tudo isso -> Run. Seguro rodar mais de uma vez.

create table if not exists veiculo_km_lancamentos (
  id bigint generated by default as identity primary key,
  veiculo_id bigint not null references veiculos (id) on delete cascade,
  -- id do registro no GPO (/v1/veiculos/lancamento) — permite reimportar
  -- sem duplicar, igual a veiculos.legacy_id. Nulo pra lançamentos feitos
  -- manualmente aqui dentro.
  legacy_id bigint,
  data_lancamento date not null,
  km numeric not null,
  responsavel_nome text,
  -- "gpo" (veio da importação única) ou "manual" (lançado aqui dentro).
  origem text not null default 'manual',
  criado_em timestamptz not null default now()
);

-- unique (não índice parcial): upsert por legacy_id (onConflict) exige uma
-- constraint/índice único "cheio" — um índice parcial (where legacy_id is
-- not null) não é aceito como alvo do ON CONFLICT gerado pelo
-- supabase-js, e nem precisa: unique já permite múltiplos NULLs (um por
-- lançamento manual) sem conflito nenhum.
alter table veiculo_km_lancamentos
  add constraint veiculo_km_lancamentos_legacy_id_key unique (legacy_id);

create index if not exists veiculo_km_lancamentos_veiculo_id_idx
  on veiculo_km_lancamentos (veiculo_id);
