-- Migração: fila de "fichas de EPI geradas aguardando atualização manual no
-- GPO" (sistema do cliente) + campo de divergência de CA nas auditorias.
--
-- Como rodar: Supabase -> seu projeto (Controle Eolen) -> SQL Editor -> New
-- query -> cola tudo isso -> Run. É seguro rodar mais de uma vez (usa "if
-- not exists"/"if exists" em tudo).

-- 1) Marca, direto na auditoria, se ela tem algum item de CA "não confere"
--    (CA digitado pelo auditor diferente do que está na Ficha de EPI da
--    pessoa) — recalculado pelo servidor a cada vez que as respostas ou o
--    status da auditoria são salvos. Usado pra decidir quando mostrar o
--    botão "Gerar ficha de EPI" na listagem, sem precisar carregar as
--    respostas completas de cada auditoria na tela de lista.
alter table auditorias
  add column if not exists tem_ca_divergente boolean not null default false;

-- 2) Fila de fichas de EPI regeneradas (CA trocado após auditoria) que ainda
--    precisam ser subidas manualmente no GPO (o GPO não tem API de escrita
--    — só leitura, usada pela sincronização existente). Cada linha é UMA
--    ficha gerada; "regularizado" é marcado quando alguém confirma que já
--    fez o upload manual no sistema do cliente.
create table if not exists gpo_pendencias (
  id bigint generated by default as identity primary key,
  treinamento_id bigint references treinamentos(id) on delete set null,
  pessoa_id bigint references pessoas(id) on delete set null,
  pessoa_nome text not null,
  auditoria_id bigint references auditorias(id) on delete set null,
  arquivo_path text not null,
  itens_alterados jsonb not null default '[]'::jsonb,
  criado_em timestamptz not null default now(),
  criado_por_id uuid,
  criado_por_nome text,
  regularizado boolean not null default false,
  regularizado_em timestamptz,
  regularizado_por_id uuid,
  regularizado_por_nome text
);

create index if not exists gpo_pendencias_regularizado_idx
  on gpo_pendencias (regularizado);

-- RLS ligado, sem policy pra ninguém — igual ao resto das tabelas deste
-- projeto: o navegador nunca fala direto com o Postgres, só através das
-- rotas /api/*, que usam a service-role key (que ignora RLS) no servidor.
alter table gpo_pendencias enable row level security;
