-- Migração: aba "Acesso" — tabela de equipes de campo (operadora, projeto(s),
-- regional(is)) e seus integrantes, com os dados/credenciais de acesso aos
-- sistemas da operadora.
--
-- Pedido do Diego (28/09/2026): uma tela nova, dentro da aba "Acesso", onde
-- a Eolen cadastra e consulta suas equipes de campo. Cada equipe pode
-- atender mais de um projeto (HUAWEI/NOKIA/ERICSSON/TELEFONICA) e mais de
-- uma regional (CO/ES/MG/NE/NO/RJ/SP/SUL) ao mesmo tempo — por isso
-- `projetos`/`regionais` são arrays, não uma coluna de texto única. A
-- Operadora (TIM/CLARO/VIVO) é uma só por equipe.
--
-- Ainda SEM a API externa de consulta (o Diego pediu pra deixar pra depois)
-- — por enquanto isso só é lido/gravado pela própria tela do Controle
-- Eolen, com a mesma permissão por usuário (`usuarios.permissoes.acesso`)
-- de qualquer outra página do sistema.
--
-- ATENÇÃO (segurança): `acesso_membros.senha` guarda em texto puro a senha
-- de acesso da pessoa a um sistema da operadora (campo já assim na planilha
-- de origem) — mesmo padrão de "sem criptografia adicional" já usado pra
-- CPF/RG no resto do sistema, mas aqui é literalmente uma senha de sistema
-- de terceiro. Recomendo fortemente restringir quem tem permissão "ver" em
-- Acesso (Administrador → Usuários) ao mínimo de pessoas necessário.
--
-- Como rodar: Supabase -> projeto Controle Eolen -> SQL Editor -> New query
-- -> cola tudo isso -> Run. Seguro rodar mais de uma vez.

create table if not exists acesso_equipes (
  id bigint generated by default as identity primary key,
  nome_equipe text not null,
  operadora text not null,
  projetos text[] not null default '{}',
  regionais text[] not null default '{}',
  atividade text,
  empresa text,
  status text,
  validade date,
  contrato text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

-- Índices GIN pra permitir busca "equipes que atendem o projeto X" /
-- "...a regional Y" com o operador `@>` (contains) — é exatamente esse tipo
-- de filtro que a futura API de consulta (e a própria tela) vai precisar.
create index if not exists acesso_equipes_projetos_idx on acesso_equipes using gin (projetos);
create index if not exists acesso_equipes_regionais_idx on acesso_equipes using gin (regionais);
create index if not exists acesso_equipes_operadora_idx on acesso_equipes (operadora);

create table if not exists acesso_membros (
  id bigint generated by default as identity primary key,
  equipe_id bigint not null references acesso_equipes(id) on delete cascade,
  funcao text,
  nome text not null,
  sobrenome text,
  rg text,
  oe text,
  cpf text,
  data_nascimento date,
  telefone_particular text,
  telefone_vivo text,
  email text,
  email_corporativo text,
  filiacao text,
  veiculo text,
  cnpj text,
  pis text,
  sap text,
  redecorp text,
  sigitm text,
  senha text,
  va_access text,
  imei text,
  atc_vivo text,
  highline_vivo text,
  ihs text,
  winity text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index if not exists acesso_membros_equipe_id_idx on acesso_membros (equipe_id);
